<a href="https://colab.research.google.com/github/SaiThrishool/MACHINE_LEARNING_LIBRARIES_AND_BASICS/blob/main/COMPLETE_NUMPY_LIBRARY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

LIST VS NUMPY - TIME TAKEN

In [2]:
from time import process_time


In [3]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.00037147099999979005


In [4]:
np_array = np.array(list(i for i in range(10000)))  # Convert generator to a list before array creation.
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.00013031099999993856


NUMPY ARRAYS

In [5]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


INITIAL PLACE HOLDERS IN NUMPY ARRYAS

In [12]:
x=np.zeros((4,5),dtype=float)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
y=np.ones((5,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [14]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
#create identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#create a numpy array with random values

In [17]:
b=np.random.random((3,4))
print(b)

[[0.69270805 0.98980748 0.64187438 0.6735564 ]
 [0.88165582 0.04217126 0.95995078 0.02715053]
 [0.52374032 0.19768457 0.43905333 0.06726662]]


In [18]:
#random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[17 36 38 93 39]
 [93 43 67 26 86]
 [63 28 74 71 14]]


In [19]:
#array of evenly spaced values
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [20]:
#array of evenly spaced values
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [21]:
#convert a list to a numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

ANALYSING NUMPY ARRAY

In [22]:
c=np.random.randint(10,90,(5,5))
print(c)

[[28 69 46 25 19]
 [21 22 22 68 50]
 [88 85 58 36 22]
 [29 23 26 29 88]
 [38 79 89 25 64]]


In [24]:
#array dimesnions
print(c.shape)

(5, 5)


In [23]:
#number of dimesnions
print(c.ndim)

2


In [25]:
#number of elemnts in an array
print(c.size)

25


In [26]:
#checking data type values in th array
print(c.dtype)

int64


MATHEMATICAL OPERATIONS ON NUMPY  ARRAY

In [27]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 7 2]
 [1 5 5]
 [9 5 2]]
[[17 18 11]
 [15 15 19]
 [11 12 14]]


In [29]:
print(a)

[[8 7 2]
 [1 5 5]
 [9 5 2]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 25 13]
 [16 20 24]
 [20 17 16]]
[[ -9 -11  -9]
 [-14 -10 -14]
 [ -2  -7 -12]]
[[136 126  22]
 [ 15  75  95]
 [ 99  60  28]]
[[0.47058824 0.38888889 0.18181818]
 [0.06666667 0.33333333 0.26315789]
 [0.81818182 0.41666667 0.14285714]]


In [31]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 20 14]
 [22 19 21]
 [19 26 21]]
[[ -3  -4 -12]
 [ -6 -19  -5]
 [ -1 -10 -15]]
[[ 88  96  13]
 [112   0 104]
 [ 90 144  54]]
[[0.72727273 0.66666667 0.07692308]
 [0.57142857 0.         0.61538462]
 [0.9        0.44444444 0.16666667]]


ARRAY MANIPULATION

In [32]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 0 6]
 [3 1 5]]
(2, 3)


In [33]:
#transpose of matrix
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[0 3]
 [0 1]
 [6 5]]
(3, 2)


In [34]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[0 3]
 [0 1]
 [6 5]]
(3, 2)


In [35]:
#reshaping arrayy
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 7 8]
 [0 4 9]]
(2, 3)


In [36]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[8 7]
 [8 0]
 [4 9]]
(3, 2)
